Eng 1652 pop out http errors to new npm repo
abs-warranty/http-errors pull request #1
Opened 2023-02-02 16:26 UTC by shellylane

2023-02-02 22:09 UTC, wtkersting requested changes

2023-02-02 22:09 UTC, wtkersting commented on README.md
> +`yarn add ../http-errors`
Remove this

2023-02-02 22:09 UTC, wtkersting commented on index.js
> + */
Can you add `@typedef`s?

2023-02-02 23:38 UTC, wtkersting requested changes

2023-02-02 23:38 UTC, wtkersting commented on index.js
> +   *
Let's keep this file clean - we can remove these empty lines for comment blocks

2023-02-02 23:38 UTC, wtkersting commented on index.js
> +   * @param {string} externalMessage
externalMessage can also be a `boolean`

2023-02-03 00:10 UTC, daverted requested changes
Take a look at https://jsdoc.app/ and add proper typedefs. I've added a few in the comments to get you started.

2023-02-03 00:10 UTC, daverted commented on index.js
> +const response = {
```suggestion
/** @type {{[key: number]: string}} */
const response = {
```

2023-02-03 00:10 UTC, daverted commented on index.js
> + */
```suggestion
 * @extends {Error}
 */
```

2023-02-03 00:10 UTC, daverted commented on index.js
> + */
```suggestion
 * @extends {HttpError}
 */
```

2023-02-06 16:27 UTC, jonnysowards requested changes

2023-02-06 16:27 UTC, jonnysowards commented on typedoc.mjs
> +main().catch(console.error)
Add a line at the end of the file.

```suggestion
main().catch(console.error)

```

2023-02-06 16:27 UTC, jonnysowards commented on typedoc.json
> +  }
Add new line at end of file.

```suggestion
  }
  
```

2023-02-06 16:27 UTC, jonnysowards commented on tsconfig.json
> +  }
Add new line at end of file.
```suggestion
  }
  
```

2023-02-06 17:02 UTC, jonnysowards approved these changes

2023-02-06 17:29 UTC, wtkersting commented on .github/workflows/publish.yaml
> +          git push
Add a new line

2023-02-06 17:29 UTC, wtkersting approved these changes
Approved, though make sure that NPM is ready to publish before merging

2023-02-06 22:02 UTC, wtkersting commented on .github/workflows/publish.yaml
> +          git push
There's still not a new line here

2023-02-06 22:15 UTC, wtkersting requested changes
Make the `externalMessage` properties `[optional]`

2023-02-06 22:15 UTC, wtkersting commented on README.md
> +To install for production:
```suggestion
To install
```

2023-02-06 22:15 UTC, wtkersting commented on src/index.js
> +   * @param {string | boolean} externalMessage
All of these `externalMessage` properties are optional - they need to be in `[]` -
```suggestion
   * @param {string | boolean} [externalMessage]
```

<img width="568" alt="image" src="https://user-images.githubusercontent.com/23663629/217099199-493095e5-1837-46fc-a97c-6babcf49a2e5.png">

2023-02-07 21:05 UTC, wtkersting approved these changes

2023-02-07 21:46 UTC, daverted approved these changes

2023-02-07 21:47 UTC, merged